document.write("<header>");
document.write("	<nav class='navbar navbar-inverse navbar-static-top'>");
document.write("		<div class='container'>");
document.write("			<div class='navbar-header'>");
document.write("				<a class='navbar-brand' href='#'>");
document.write("					<img alt='Brand' src='./images/index.png'>");
document.write("				</a>");
document.write("			</div>");

document.write("			<div class='collapse navbar-collapse navbar-right'>");
document.write("				<p class='navbar-text'>欢迎您</p>");
document.write("				<ul class=\"nav navbar-nav\">");
document.write("					<li class='dropdown'>");
document.write("						<a href='#' class='dropdown-toggle' data-toggle='dropdown' ");
document.write("							role='button' aria-expanded='false' id='loginuser_a'>");
document.write("						</a>");
document.write("						<ul class='dropdown-menu' role='menu'>");
document.write("							<li><a href='#' id='logout_a'>退出</a></li>");
document.write("						</ul>");
document.write("					</li>");
document.write("				</ul>");
document.write("				<form class='navbar-form navbar-left' role='search'>");
document.write("					<div class='form-group'>");
document.write("						<input type='text' class='form-control' placeholder='Search'>");
document.write("					</div>");
document.write("					<button type='submit' class='btn btn-default'>Submit</button>");
document.write("				</form>");
document.write("				<ul class='nav navbar-nav'>");
document.write("					<li><a href='#'>系统消息<span class='badge'>3</span></a></li>");
document.write("				</ul>");
document.write("			</div>");
document.write("		</div>");
document.write("	</nav>");
document.write("</header>");
